[project]
name = "energy-dependent-colvolve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numba>=0.60.0",
    "numpy>=2.0.2",
    "pytest>=8.4.0",
    "requests>=2.32.3",
]
